# Generated by Django 3.1 on 2021-03-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readdetail',
            old_name='data',
            new_name='date',
        ),
    ]
