# Generated by Django 3.1 on 2021-03-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210322_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogReadNum',
        ),
    ]
